### ISSUE TITLE
Copy username

### ISSUE THREAD

**Issue by mostepunk** [shikaan/keydex#14]
It would be nice copy not only password, but also username.

**Comment by shikaan** [comment]
Hey! Thanks for this comment (: 
I'll try taking a look over the weekend and will keep you posted here. If you have expertise and want to contribute, feel free to open a pull request; I'd be happy to assist

**Comment by shikaan** [comment]
Hey @mostepunk,
Sorry for the late reply, life got a lot in the way lately.

So much so that I forgot the feature is already implemented :sweat_smile: 

[Screencast from 04-07-23 22:56:20.webm](https://github.com/shikaan/keydex/assets/17052868/74d91eee-f066-41bb-9d68-080d20a3bdfc)

This is a quick screencast showcasing the feature. You can move on the fields with arrows and use Ctrl+C to copy the field.

Or did you have something else in mind? Maybe for the `copy` command?

**Comment by mostepunk** [comment]
Hi @shikaan!
I want to integrate keydex to dmenu. 
```bas
keydex list | dmenu-run| keydex copy  
```
But I want to create one script for copy password, and another for copy username. I didn't find how can realize with keydex.

**Comment by shikaan** [comment]
Hey @mostepunk, I think this makes totally sense.

What do you think of the following interface?

```
keydex copy --field=UserName
```

So that you can copy any field of the entry

**Comment by shikaan** [comment]
I took a quick stab at it [here](https://github.com/shikaan/keydex/pull/15). If it makes sense to you I'll go ahead and merge it tomorrow

**Comment by shikaan** [comment]
Went through the code again and tried it with dmenu myself. 

It'll look something like `keydex list | dmenu | keydex copy -fUsername`

I am merging it now, feel free to reopen this thread if it does not work or you have further suggestions

**Comment by mostepunk** [comment]
Thanks a lot! I'll try it in a few days
